import { FacultyProfile } from '@/types';

export const VFSTR_FACULTY_SEED: FacultyProfile[] = [
  {
    id: 'fac_001',
    employeeId: 'VFSTR-FAC-101',
    fullName: 'Dr. K. V. Krishna Kishore',
    department: 'Computer Science & Engineering',
    designation: 'Professor & Dean IT Services',
    email: 'dean_it@vignan.ac.in',
    phoneNumber: '+91 98480 12345',
    cabinLocation: 'A-Block 3rd Floor, Cabin 304',
    bloodGroup: 'O+',
    payrollDeductionEnabled: true,
    assignedRouteId: 'rt_vijayawada_exp_01',
    assignedStopId: 'stop_benz_circle',
    passStatus: 'active',
  },
  {
    id: 'fac_002',
    employeeId: 'VFSTR-FAC-102',
    fullName: 'Dr. N. Veeranjaneyulu',
    department: 'Information Technology',
    designation: 'Professor & HoD',
    email: 'hod_it@vignan.ac.in',
    phoneNumber: '+91 94401 54321',
    cabinLocation: 'NTR Vignan Library, 2nd Floor',
    bloodGroup: 'B+',
    payrollDeductionEnabled: true,
    assignedRouteId: 'rt_guntur_local_04',
    assignedStopId: 'stop_collectorate',
    passStatus: 'active',
  },
  {
    id: 'fac_003',
    employeeId: 'VFSTR-FAC-103',
    fullName: 'Dr. M. S. S. Rukmini',
    department: 'Electronics & Communication Engineering',
    designation: 'Associate Professor',
    email: 'rukmini_ece@vignan.ac.in',
    phoneNumber: '+91 99890 67890',
    cabinLocation: 'U-Block Ground Floor',
    bloodGroup: 'A+',
    payrollDeductionEnabled: true,
    assignedRouteId: 'rt_tenali_02',
    assignedStopId: 'stop_tenali_bypass',
    passStatus: 'active',
  },
  {
    id: 'fac_004',
    employeeId: 'VFSTR-FAC-104',
    fullName: 'Dr. G. Srinivasa Rao',
    department: 'Mechanical Engineering',
    designation: 'Professor',
    email: 'srinivas_mech@vignan.ac.in',
    phoneNumber: '+91 97012 34567',
    cabinLocation: 'Workshop Complex Cabin 12',
    bloodGroup: 'AB+',
    payrollDeductionEnabled: false,
    assignedRouteId: 'rt_mangalagiri_05',
    assignedStopId: 'stop_mangalagiri_bypass',
    passStatus: 'active',
  },
  {
    id: 'fac_005',
    employeeId: 'VFSTR-FAC-105',
    fullName: 'Dr. S. Krupanidhi',
    department: 'Biotechnology',
    designation: 'Dean of Sciences & Professor',
    email: 'dean_sciences@vignan.ac.in',
    phoneNumber: '+91 98495 87654',
    cabinLocation: 'Bio-Valley Block 2nd Floor',
    bloodGroup: 'O-',
    payrollDeductionEnabled: true,
    assignedRouteId: 'rt_vijayawada_exp_01',
    assignedStopId: 'stop_ramavarappadu_ring',
    passStatus: 'active',
  }
];
